### ISSUE TITLE
Wrong result！！！

### ISSUE THREAD

**Issue by Xjmengnieer** [SHI-Labs/VMFormer#14]
I ran your inference_vm.py file and saved the predictions like RVM and then did the test, the results I got did not match your paper!
![image](https://user-images.githubusercontent.com/88227513/204086326-6cb49b8d-7016-4af0-b6f1-90fa127b3606.png)
![image](https://user-images.githubusercontent.com/88227513/204086375-385fef10-2543-46b0-a1d2-fa0515e5a1dd.png)

could you give me some advice?

**Comment by Xjmengnieer** [comment]
And if we save the image directly with the to_pil_image function, we will get an even worse image！
![image](https://user-images.githubusercontent.com/88227513/204086514-ec1fb486-6044-48dc-a22f-3ff5c9db5d81.png)
![image](https://user-images.githubusercontent.com/88227513/204086532-cba61682-b78e-49d1-b54f-faef61a3f9bc.png)

**Comment by chrisjuniorli** [comment]
Thanks for posting this issue.

1. In terms of the performance, I assume you are referring to Table 3, it seems only phd_mad is not matching. We'll give a test on our device and share feedback here.

2. For visualization, do outputs of all frames have this issue or only happen to a specific frame or a particular clip?

We'll release a major update of the repo in the coming week, stay tuned! Thanks

**Comment by chrisjuniorli** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/29687423/204195270-23792ced-6829-4ff4-8c6d-625001986977.png">
We just did a test and got the exactly same number in Table 3. Did you make more modifications in inference_vm.py, like reset pha_mad after the iteration on a clip?

**Comment by chrisjuniorli** [comment]
and for visualization, you use `mask[0]` without `sigmoid()` , which could be the reason for the bad visualization result

**Comment by Xjmengnieer** [comment]
> 

1：Thank you for your patience in replying. Are you saving the prediction results and then testing them? An online test following your inference_vm.py file will give you this result. like this:
![image](https://user-images.githubusercontent.com/88227513/204203371-c2c7ac97-267a-480c-bb34-ce087d9aca00.png)

2：However, when I first save the prediction results and then test them with RVM's evaluate_lr.py file, I get the following results：

**Comment by Xjmengnieer** [comment]
1：Thank you for your patience in replying. Are you saving the prediction results and then testing them? An online test following your inference_vm.py file will give you this result. like this:
![image](https://user-images.githubusercontent.com/88227513/204204640-1c0f4cdb-12bd-49d2-a0d9-ca12be5abbb8.png)


2：However, when I first save the prediction results and then test them with RVM's evaluate_lr.py file, I get the following results：
![image](https://user-images.githubusercontent.com/88227513/204204677-837f22d7-d5ee-493a-8f53-20638f46bb1b.png)

I did not modify your inference_vm.py file and used the following command：
![image](https://user-images.githubusercontent.com/88227513/204204930-7cdb5ace-5642-4ca8-97a2-a99932ee5234.png)

**Comment by Xjmengnieer** [comment]
As shown in the picture, the red box is the only modification I made, simply saving the picture：
![image](https://user-images.githubusercontent.com/88227513/204205144-193d24e5-99a7-4cba-96c1-d42095023c1d.png)

**Comment by chrisjuniorli** [comment]
I used online testing without saving the results first. I think converting `np.float32` to `np.unit8` brings deviation here, because when the saved image is read in and converted to grayscale [0,1], the number would change due to the approximation. MAD is also more sensitive to the approximation since it's based on L1 distance.

**Comment by Xjmengnieer** [comment]
That's what I thought. I noticed that the data in your table 3 is exactly the same as RVM, are these data directly referenced from RVM? If so, I think the comparison here may not be appropriate.

**Comment by chrisjuniorli** [comment]
The data in Table 3 is exactly the same as the testing data used in RVM. We'll test RVM under the online setting and see if there also exists a performance degradation on MAD. If so, we'll use the same setting and update Table 3 accordingly. Thanks for pointing out this issue.

**Comment by Xjmengnieer** [comment]
No matter, this is still a good paper.
