### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by dogyoonlee** [SHI-Labs/VMFormer#4]
I appreciate to your awesome work!

However, I wonder the dataset you used.
Did your project experiments on only human class or all the classes like some other video matting papers(e.g. DVM)?

**Comment by chrisjuniorli** [comment]
Thanks for your interest! 

We only use human classes as foregrounds from VideoMatte240K: https://grail.cs.washington.edu/projects/background-matting-v2/#/datasets
