### ISSUE TITLE
Inference not working. torchvision.models.utils not found.

### ISSUE THREAD

**Issue by cheetahfightfx** [SHI-Labs/VMFormer#5]
python3 inference_vm.py --model_path checkpoint/vmformer_mv3.pth --img_path frames
Traceback (most recent call last):
  File "/hdd3/vplai/vmformer/inference_vm.py", line 25, in <module>
    from models import build_model
  File "/hdd3/vplai/vmformer/models/__init__.py", line 9, in <module>
    from .vmformer import build_vm
  File "/hdd3/vplai/vmformer/models/vmformer.py", line 23, in <module>
    from .backbone import build_backbone
  File "/hdd3/vplai/vmformer/models/backbone.py", line 29, in <module>
    from .mv3 import MobileNetV3LargeEncoder
  File "/hdd3/vplai/vmformer/models/mv3.py", line 3, in <module>
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'

------------------------------------

Python version 3.9
Conda environment created.
Pytorch latest version installed with

conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
MultiScaleDeformableAttention==1.0 compiled and installed.

**Comment by chrisjuniorli** [comment]
could you try the same pytorch and torchvision version as we used here:
conda install pytorch==1.9.0 torchvision==0.10.0 -c pytorch

**Comment by chrisjuniorli** [comment]
If not more followups on this issue, I'll close it

**Comment by cheetahfightfx** [comment]
Hi, 

I tried with 

conda install pytorch==1.9.0 torchvision==0.10.0 -c pytorch

Didn't work. Inference error was no cuda libraries.

When I tried with cuda version 11.3, it came up with the same error

Traceback (most recent call last):
File "/hdd3/vplai/vmformer/inference_vm.py", line 25, in
from models import build_model
File "/hdd3/vplai/vmformer/models/init.py", line 9, in
from .vmformer import build_vm
File "/hdd3/vplai/vmformer/models/vmformer.py", line 23, in
from .backbone import build_backbone
File "/hdd3/vplai/vmformer/models/backbone.py", line 29, in
from .mv3 import MobileNetV3LargeEncoder
File "/hdd3/vplai/vmformer/models/mv3.py", line 3, in
from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'

**Comment by chrisjuniorli** [comment]
Can you try to reinstall it under cuda 11.1, since torchvision-related codes seem break a lot under 11.3 like [here](https://github.com/xingyizhou/CenterTrack/issues/134)

**Comment by cheetahfightfx** [comment]
Tried with 11.1. Here is the error

`RuntimeError:
The detected CUDA version (11.4) mismatches the version that was used to compile
PyTorch (10.2). Please make sure to use the same CUDA versions.`

The error happened while trying to `sh make.sh`

**Comment by chrisjuniorli** [comment]
I think it indicates that your CUDA is 11.4 and your PyTorch is compiled under CUDA 10.2. Can you try to reinstall your PyTorch under CUDA 11.4?

**Comment by chrisjuniorli** [comment]
I closed this issue since no further response and free feel to reopen it if you have more questions.
