### ISSUE TITLE
about  FPS，Have you tested the model reasoning speed to see if it can reach RVM speed

### ISSUE THREAD

**Issue by zhanghongyong123456** [SHI-Labs/VMFormer#8]
![image](https://user-images.githubusercontent.com/48466610/191424367-cc9446cc-68aa-45a9-b4c0-5b934c35d977.png)
I wonder if I can do 4K real time？

**Comment by chrisjuniorli** [comment]
We haven't tested under 4K/HD input. Compared to RVM, we tested under low-resolution inputs in Table 2, RVM reaches 149FPS and our model is 54FPS. I believe it couldn't reach real-time inference under 4K input for now and we're working on making it faster for inference. Thanks!

**Comment by zhanghongyong123456** [comment]
> We haven't tested under 4K/HD input. Compared to RVM, we tested under low-resolution inputs in Table 2, RVM reaches 149FPS and our model is 54FPS. I believe it couldn't reach real-time inference under 4K input for now and we're working on making it faster for inference. Thanks!

Okay, thank you very much,
